# Generated by Django 5.1.5 on 2025-01-14 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='friendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requeststatus', models.CharField(choices=[('pendingrq', 'Pendingrq'), ('acceptedrq', 'Acceptedrq')], default='pendingrq', max_length=10)),
                ('rqsentat', models.DateTimeField(auto_now_add=True)),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
