# Generated by Django 5.1.1 on 2025-01-16 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2003, 12, 30), verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
